#! /bin/bash

outdir="."
blob_count=514


#
# Get all the information collected in the different threads above into one 
# set of files
#
for ((i=1; i<=$blob_count; i++)); do
    cat $outdir/vulnerable.md.$i >> $outdir/vulnerable.md
    cat $outdir/not-vulnerable.md.$i >> $outdir/not-vulnerable.md
    cat $outdir/unknown.md.$i >> $outdir/unknown.md
    rm $outdir/vulnerable.md.$i $outdir/not-vulnerable.md.$i $outdir/unknown.md.$i
done


#
# Collect stats to output 
#
num_vulnerable=`grep "^project =" $outdir/vulnerable.md | sort | uniq | wc -l`
num_not_vulnerable=`grep "^project =" $outdir/not-vulnerable.md | sort | uniq | wc -l`
num_unknown=`grep "^project =" $outdir/unknown.md | sort | uniq | wc -l`

#
# Output information about this commit
#


echo "<h1>Commit that fixes a vulnerability:</h1>" >> $outdir/index.md
echo "$fixed_commit" >> $outdir/index.md
echo "<p />" >> $outdir/index.md
echo "<h1>Information about the above commit</h1>" >> $outdir/index.md

echo "<a href=blobs.md>Blobs and filenames</a> in commit $fixed_commit<br />" >> $outdir/index.md
echo "<a href=bad_blobs.txt>Ancestors </a> of the above blobs, which are before the fixing commit, thus presumably vulnerable. (recursive b2ob)<br />" >> $outdir/index.md
echo "<a href=good_blobs.txt>Descendants </a> of the fixed blobs, which presumably also contain the fix. (recursive ob2b)<br />" >> $outdir/index.md
echo "<p />" >> $outdir/index.md

echo "<h1>Projects which have contained one of the presumably vulnerable blobs:</h1>" >> $outdir/index.md
echo "$num_vulnerable <a href="vulnerable.md">Vulnerable Projects</a> (Known to contain presumably vulnerable blob in the most current revision)<br />" >> $outdir/index.md
echo "$num_not_vulnerable <a href="not-vulnerable.md">Not Vulnerable Projects</a> (Known to contain a fixed version in the most current revision)<br />" >> $outdir/index.md
echo "$num_unknown <a href="unknown.md">Unknown Projects</a> (Presumably vulnerable code has been changed in most current revision, unknown if the changes fixes vulnerability)<br />" >> $outdir/index.md
echo "<p />" >> $outdir/index.md
